### ISSUE TITLE
Using parseFloat for type casting

### ISSUE THREAD

**Issue by mangvlad** [worldline/swagger-jack#14]
cast utility function appears to be using parseFloat for all numbers.
This results in this string '12345xyz' to be casted to '12345' and becomes a valid number.

I think there should be an option to require "strict" validation, so this input should be rejected as invalid...

Maybe something like this in cast function (just like it is done for string):

```
    case 'integer':
        if(!isNaN(Number(value))){
            original = value;
            value = value !== void 0 ? parseFloat(value) : void 0;
            value = isNaN(value) ? original : value;
        }
```

**Comment by simonlopez** [comment]
The correct way is:
`when 'number', 'integer'
    original = value
    value = if value isnt undefined and value isnt '' then Number(value) else undefined
    value = if isNaN(value) then original else value`

apiValidator will do the final validation
