### ISSUE TITLE
Stupid err from a newbie

### ISSUE THREAD

**Issue by gcomesana** [worldline/swagger-jack#3]
Hi
I just started to use your swagger companion/wrapper and, after trying a very simple example I get a very weird error. 
The simple code is (in CS, call it server.coffee):

``` coffeescript
# Modules
express = require 'express'
http = require 'http'
partials = require 'express-partials'
app = express()

swagger = require 'swagger-jack'

# Boot setup: autoload lib and controllers
# require("#{__dirname}/../config/boot")(app)

# Configuration
app.configure ->
  port = process.env.PORT || 3010
  if process.argv.indexOf('-p') >= 0
    port = process.argv[process.argv.indexOf('-p') + 1]

  app.set 'port', port
  app.use express.favicon()
  app.use express.logger('dev')
  app.use express.bodyParser()
  app.use express.methodOverride()
#  app.use app.router

app.configure 'development', ->
  app.use express.errorHandler()

generalDescriptor =
    apiVersion: '1.0',
    basePath: '/apidoc'

app.use swagger.generator app, generalDescriptor, [
    api:
        resourcePath: ''
        apis: [
            path: '/'
            operations: [
                httpMethod: 'GET'
                nickname: 'getroot'
            ]
        ]
    controller:
        getroot: (req, resp, next) ->
            resp.send 'this is the root'
]

app.listen(app.get('port'))
console.log "Listening this time on port #{app.get('port')}"
```

You can see more requires than required but this is an snippet which was generated from a node boilerplate. The response when I trying to startup the node server is, always:

```
/usr/local/bin/node server.js
Listening this time on port 3010

timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
Error: Router#get() requires a path
    at Router.route (/Users/bioinfo/Development/coffee/express-api/node_modules/express/lib/router/index.js:245:20)
    at Router.methods.forEach.Router.(anonymous function) [as get] (/Users/bioinfo/Development/coffee/express-api/node_modules/express/lib/router/index.js:270:16)
    at Function.methods.forEach.app.(anonymous function) [as get] (/Users/bioinfo/Development/coffee/express-api/node_modules/express/lib/application.js:412:26)
    at module.exports.app.descriptor (/Users/bioinfo/Development/coffee/express-api/node_modules/swagger-jack/lib/generator.js:165:40)
    at Object._.delay [as _onTimeout] (/Users/bioinfo/Development/coffee/express-api/node_modules/swagger-jack/node_modules/underscore/underscore.js:616:47)
    at Timer.list.ontimeout (timers.js:101:19)
```

Even if I compile the CS code into JS, the error is the same (I supposed it could be a CS problem, but unfortunately I was wrong). May you see, as the creator, whether I have anything wrong with the configuration or so?

BTW, it seems a great job, as you point clearer than swagger-node-express, and with lots of tests, which is very right. I just miss a working example, I will be able to provide you if I can get this thing work

Zanx in advance.

w i l l y

**Comment by feugy** [comment]
Hello Willy.

I did not try it yet, but I'm pretty sure the cause is the `path: '/'`. 
REST is about managing resources, and resources cannot be anonymous. I'll try to reproduce it and see if it's relevant to have resources with empty path, but I guess that you can fix this by having anything behind your leading /;

Let me know if it helps you.

feugy

**Comment by gcomesana** [comment]
Hi there
thank you for the feedback. It worked along with a couple of more patches. You can close the issue, if so. I will be able to send you an example to improve the documentation or include it in the code after trying a couple of things more, hopefully this weekend.

cheers again!!!
w i l l y

**Comment by feugy** [comment]
ok !
