### ISSUE TITLE
Swagger path

### ISSUE THREAD

**Issue by mangvlad** [worldline/swagger-jack#6]
It looks like swagger path is hard codded to api-docs.json.
Any way to make it configurable so api-docs or v1/api-docs can be used instead?

Thanks.

**Comment by feugy** [comment]
I'm currently working on it: you'll be able to set your own descriptor path when adding the generator middleware on your express application:

```
var app = express();
app.use(express.cookieParser())
  .use(express.methodOverride())
  .use(express.bodyParser())
  .use(swagger.generator(
    app, 
    {apiVersion: '1.0', ...}, 
    [{api: require('./api.yml'), controller: require('./controller')}], 
    {descPath: '/v1/api-docs'}
  ));
```

Stay tunned for version 1.4.0 !
